"""empty message

Revision ID: 467eb3f93699
Revises: a0c296fb5401
Create Date: 2021-05-08 13:50:35.935521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467eb3f93699'
down_revision = 'a0c296fb5401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_package')
    # ### end Alembic commands ###
