"""empty message

Revision ID: 58faf723ca01
Revises: 
Create Date: 2021-05-07 23:50:21.201121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58faf723ca01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_title', sa.String(length=100), nullable=True),
    sa.Column('about_txt', sa.String(length=200), nullable=True),
    sa.Column('about_details', sa.String(length=250), nullable=True),
    sa.Column('about_img', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    # ### end Alembic commands ###
